-- Create playlists table
create table playlists (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  type text not null check (type in ('category', 'country')),
  url text unique not null,
  is_active boolean default true,
  last_imported_at timestamptz,
  created_at timestamptz default now()
);

-- Enable RLS for playlists table
alter table playlists enable row level security;

-- Create policy for playlists (admins have full access)
create policy "Admins have full access on playlists"
  on playlists for all
  using (true)
  with check (true);

-- Add flag_emoji column to countries
alter table countries add column if not exists flag_emoji text;

-- Seed default Category playlists
insert into playlists (name, type, url) values
  ('Movies', 'category', 'https://iptv-org.github.io/iptv/categories/movies.m3u'),
  ('Sports', 'category', 'https://iptv-org.github.io/iptv/categories/sports.m3u'),
  ('News', 'category', 'https://iptv-org.github.io/iptv/categories/news.m3u'),
  ('Documentary', 'category', 'https://iptv-org.github.io/iptv/categories/documentary.m3u'),
  ('Kids', 'category', 'https://iptv-org.github.io/iptv/categories/kids.m3u'),
  ('Entertainment', 'category', 'https://iptv-org.github.io/iptv/categories/entertainment.m3u'),
  ('Music', 'category', 'https://iptv-org.github.io/iptv/categories/music.m3u'),
  ('Series', 'category', 'https://iptv-org.github.io/iptv/categories/series.m3u'),
  ('Animation', 'category', 'https://iptv-org.github.io/iptv/categories/animation.m3u')
on conflict (url) do nothing;

-- Insert or Update Countries with Flags (from playlist.md)
insert into countries (name, code, flag_emoji, sort_order) values
  ('Afghanistan', 'AF', '🇦🇫', 0),
  ('Albania', 'AL', '🇦🇱', 0),
  ('Algeria', 'DZ', '🇩🇿', 0),
  ('Andorra', 'AD', '🇦🇩', 0),
  ('Angola', 'AO', '🇦🇴', 0),
  ('Antigua and Barbuda', 'AG', '🇦🇬', 0),
  ('Argentina', 'AR', '🇦🇷', 0),
  ('Armenia', 'AM', '🇦🇲', 0),
  ('Aruba', 'AW', '🇦🇼', 0),
  ('Australia', 'AU', '🇦🇺', 0),
  ('Austria', 'AT', '🇦🇹', 0),
  ('Azerbaijan', 'AZ', '🇦🇿', 0),
  ('Bahamas', 'BS', '🇧🇸', 0),
  ('Bahrain', 'BH', '🇧🇭', 0),
  ('Bangladesh', 'BD', '🇧🇩', 0),
  ('Barbados', 'BB', '🇧🇧', 0),
  ('Belarus', 'BY', '🇧🇾', 0),
  ('Belgium', 'BE', '🇧🇪', 0),
  ('Belize', 'BZ', '🇧🇿', 0),
  ('Benin', 'BJ', '🇧🇯', 0),
  ('Bolivia', 'BO', '🇧🇴', 0),
  ('Bonaire', 'BQ', '🇧🇶', 0),
  ('Bosnia and Herzegovina', 'BA', '🇧🇦', 0),
  ('Brazil', 'BR', '🇧🇷', 0),
  ('British Virgin Islands', 'VG', '🇻🇬', 0),
  ('Brunei', 'BN', '🇧🇳', 0),
  ('Bulgaria', 'BG', '🇧🇬', 0),
  ('Burkina Faso', 'BF', '🇧🇫', 0),
  ('Cambodia', 'KH', '🇰🇭', 0),
  ('Cameroon', 'CM', '🇨🇲', 0),
  ('Canada', 'CA', '🇨🇦', 0),
  ('Cape Verde', 'CV', '🇨🇻', 0),
  ('Chad', 'TD', '🇹🇩', 0),
  ('Chile', 'CL', '🇨🇱', 0),
  ('China', 'CN', '🇨🇳', 0),
  ('Colombia', 'CO', '🇨🇴', 0),
  ('Comoros', 'KM', '🇰🇲', 0),
  ('Costa Rica', 'CR', '🇨🇷', 0),
  ('Croatia', 'HR', '🇭🇷', 0),
  ('Cuba', 'CU', '🇨🇺', 0),
  ('Curacao', 'CW', '🇨🇼', 0),
  ('Cyprus', 'CY', '🇨🇾', 0),
  ('Czech Republic', 'CZ', '🇨🇿', 0),
  ('Democratic Republic of the Congo', 'CD', '🇨🇩', 0),
  ('Denmark', 'DK', '🇩🇰', 0),
  ('Dominican Republic', 'DO', '🇩🇴', 0),
  ('Ecuador', 'EC', '🇪🇨', 0),
  ('Egypt', 'EG', '🇪🇬', 0),
  ('El Salvador', 'SV', '🇸🇻', 0),
  ('Equatorial Guinea', 'GQ', '🇬🇶', 0),
  ('Eritrea', 'ER', '🇪🇷', 0),
  ('Estonia', 'EE', '🇪🇪', 0),
  ('Ethiopia', 'ET', '🇪🇹', 0),
  ('Faroe Islands', 'FO', '🇫🇴', 0),
  ('Finland', 'FI', '🇫🇮', 0),
  ('France', 'FR', '🇫🇷', 0),
  ('French Guiana', 'GF', '🇬🇫', 0),
  ('French Polynesia', 'PF', '🇵🇫', 0),
  ('Gambia', 'GM', '🇬🇲', 0),
  ('Georgia', 'GE', '🇬🇪', 0),
  ('Germany', 'DE', '🇩🇪', 0),
  ('Ghana', 'GH', '🇬🇭', 0),
  ('Greece', 'GR', '🇬🇷', 0),
  ('Guadeloupe', 'GP', '🇬🇵', 0),
  ('Guam', 'GU', '🇬🇺', 0),
  ('Guatemala', 'GT', '🇬🇹', 0),
  ('Guernsey', 'GG', '🇬🇬', 0),
  ('Guinea', 'GN', '🇬🇳', 0),
  ('Guyana', 'GY', '🇬🇾', 0),
  ('Haiti', 'HT', '🇭🇹', 0),
  ('Honduras', 'HN', '🇭🇳', 0),
  ('Hong Kong', 'HK', '🇭🇰', 0),
  ('Hungary', 'HU', '🇭🇺', 0),
  ('Iceland', 'IS', '🇮🇸', 0),
  ('India', 'IN', '🇮🇳', 0),
  ('Indonesia', 'ID', '🇮🇩', 0),
  ('Iran', 'IR', '🇮🇷', 0),
  ('Iraq', 'IQ', '🇮🇶', 0),
  ('Ireland', 'IE', '🇮🇪', 0),
  ('Israel', 'IL', '🇮🇱', 0),
  ('Italy', 'IT', '🇮🇹', 0),
  ('Ivory Coast', 'CI', '🇨🇮', 0),
  ('Jamaica', 'JM', '🇯🇲', 0),
  ('Japan', 'JP', '🇯🇵', 0),
  ('Jordan', 'JO', '🇯🇴', 0),
  ('Kazakhstan', 'KZ', '🇰🇿', 0),
  ('Kenya', 'KE', '🇰🇪', 0),
  ('Kosovo', 'XK', '🇽🇰', 0),
  ('Kuwait', 'KW', '🇰🇼', 0),
  ('Kyrgyzstan', 'KG', '🇰🇬', 0),
  ('Laos', 'LA', '🇱🇦', 0),
  ('Latvia', 'LV', '🇱🇻', 0),
  ('Lebanon', 'LB', '🇱🇧', 0),
  ('Libya', 'LY', '🇱🇾', 0),
  ('Liechtenstein', 'LI', '🇱🇮', 0),
  ('Lithuania', 'LT', '🇱🇹', 0),
  ('Luxembourg', 'LU', '🇱🇺', 0),
  ('Macao', 'MO', '🇲🇴', 0),
  ('Madagascar', 'MG', '🇲🇬', 0),
  ('Malaysia', 'MY', '🇲🇾', 0),
  ('Maldives', 'MV', '🇲🇻', 0),
  ('Mali', 'ML', '🇲🇱', 0),
  ('Malta', 'MT', '🇲🇹', 0),
  ('Martinique', 'MQ', '🇲🇶', 0),
  ('Mauritania', 'MR', '🇲🇷', 0),
  ('Mauritius', 'MU', '🇲🇺', 0),
  ('Mexico', 'MX', '🇲🇽', 0),
  ('Moldova', 'MD', '🇲🇩', 0),
  ('Monaco', 'MC', '🇲🇨', 0),
  ('Mongolia', 'MN', '🇲🇳', 0),
  ('Montenegro', 'ME', '🇲🇪', 0),
  ('Morocco', 'MA', '🇲🇦', 0),
  ('Mozambique', 'MZ', '🇲🇿', 0),
  ('Myanmar', 'MM', '🇲🇲', 0),
  ('Namibia', 'NA', '🇳🇦', 0),
  ('Nepal', 'NP', '🇳🇵', 0),
  ('Netherlands', 'NL', '🇳🇱', 0),
  ('New Zealand', 'NZ', '🇳🇿', 0),
  ('Nicaragua', 'NI', '🇳🇮', 0),
  ('Niger', 'NE', '🇳🇪', 0),
  ('Nigeria', 'NG', '🇳🇬', 0),
  ('North Korea', 'KP', '🇰🇵', 0),
  ('North Macedonia', 'MK', '🇲🇰', 0),
  ('Norway', 'NO', '🇳🇴', 0),
  ('Oman', 'OM', '🇴🇲', 0),
  ('Pakistan', 'PK', '🇵🇰', 0),
  ('Palestine', 'PS', '🇵🇸', 0),
  ('Panama', 'PA', '🇵🇦', 0),
  ('Papua New Guinea', 'PG', '🇵🇬', 0),
  ('Paraguay', 'PY', '🇵🇾', 0),
  ('Peru', 'PE', '🇵🇪', 0),
  ('Philippines', 'PH', '🇵🇭', 0),
  ('Poland', 'PL', '🇵🇱', 0),
  ('Portugal', 'PT', '🇵🇹', 0),
  ('Puerto Rico', 'PR', '🇵🇷', 0),
  ('Qatar', 'QA', '🇶🇦', 0),
  ('Republic of the Congo', 'CG', '🇨🇬', 0),
  ('Reunion', 'RE', '🇷🇪', 0),
  ('Romania', 'RO', '🇷🇴', 0),
  ('Russia', 'RU', '🇷🇺', 0),
  ('Rwanda', 'RW', '🇷🇼', 0),
  ('Saint Kitts and Nevis', 'KN', '🇰🇳', 0),
  ('Saint Lucia', 'LC', '🇱🇨', 0),
  ('Samoa', 'WS', '🇼🇸', 0),
  ('San Marino', 'SM', '🇸🇲', 0),
  ('Saudi Arabia', 'SA', '🇸🇦', 0),
  ('Senegal', 'SN', '🇸🇳', 0),
  ('Serbia', 'RS', '🇷🇸', 0),
  ('Singapore', 'SG', '🇸🇬', 0),
  ('Sint Maarten', 'SX', '🇸🇽', 0),
  ('Slovakia', 'SK', '🇸🇰', 0),
  ('Slovenia', 'SI', '🇸🇮', 0),
  ('Somalia', 'SO', '🇸🇴', 0),
  ('South Africa', 'ZA', '🇿🇦', 0),
  ('South Korea', 'KR', '🇰🇷', 0),
  ('Spain', 'ES', '🇪🇸', 0),
  ('Sri Lanka', 'LK', '🇱🇰', 0),
  ('Sudan', 'SD', '🇸🇩', 0),
  ('Suriname', 'SR', '🇸🇷', 0),
  ('Sweden', 'SE', '🇸🇪', 0),
  ('Switzerland', 'CH', '🇨🇭', 0),
  ('Syria', 'SY', '🇸🇾', 0),
  ('Taiwan', 'TW', '🇹🇼', 0),
  ('Tajikistan', 'TJ', '🇹🇯', 0),
  ('Tanzania', 'TZ', '🇹🇿', 0),
  ('Thailand', 'TH', '🇹🇭', 0),
  ('Togo', 'TG', '🇹🇬', 0),
  ('Trinidad and Tobago', 'TT', '🇹🇹', 0),
  ('Tunisia', 'TN', '🇹🇳', 0),
  ('Turkiye', 'TR', '🇹🇷', 0),
  ('Turkmenistan', 'TM', '🇹🇲', 0),
  ('Uganda', 'UG', '🇺🇬', 0),
  ('Ukraine', 'UA', '🇺🇦', 0),
  ('United Arab Emirates', 'AE', '🇦🇪', 0),
  ('United Kingdom', 'UK', '🇬🇧', 0),
  ('United States', 'US', '🇺🇸', 0),
  ('Uruguay', 'UY', '🇺🇾', 0),
  ('Uzbekistan', 'UZ', '🇺🇿', 0),
  ('Vatican City', 'VA', '🇻🇦', 0),
  ('Venezuela', 'VE', '🇻🇪', 0),
  ('Vietnam', 'VN', '🇻🇳', 0),
  ('Western Sahara', 'EH', '🇪🇭', 0),
  ('Yemen', 'YE', '🇾🇪', 0),
  ('Zimbabwe', 'ZW', '🇿🇼', 0)
on conflict (code) do update set flag_emoji = excluded.flag_emoji;

-- Seed all country playlists (from playlist.md)
insert into playlists (name, type, url) values
  ('Afghanistan', 'country', 'https://iptv-org.github.io/iptv/countries/af.m3u'),
  ('Albania', 'country', 'https://iptv-org.github.io/iptv/countries/al.m3u'),
  ('Algeria', 'country', 'https://iptv-org.github.io/iptv/countries/dz.m3u'),
  ('Andorra', 'country', 'https://iptv-org.github.io/iptv/countries/ad.m3u'),
  ('Angola', 'country', 'https://iptv-org.github.io/iptv/countries/ao.m3u'),
  ('Antigua and Barbuda', 'country', 'https://iptv-org.github.io/iptv/countries/ag.m3u'),
  ('Argentina', 'country', 'https://iptv-org.github.io/iptv/countries/ar.m3u'),
  ('Armenia', 'country', 'https://iptv-org.github.io/iptv/countries/am.m3u'),
  ('Aruba', 'country', 'https://iptv-org.github.io/iptv/countries/aw.m3u'),
  ('Australia', 'country', 'https://iptv-org.github.io/iptv/countries/au.m3u'),
  ('Austria', 'country', 'https://iptv-org.github.io/iptv/countries/at.m3u'),
  ('Azerbaijan', 'country', 'https://iptv-org.github.io/iptv/countries/az.m3u'),
  ('Bahamas', 'country', 'https://iptv-org.github.io/iptv/countries/bs.m3u'),
  ('Bahrain', 'country', 'https://iptv-org.github.io/iptv/countries/bh.m3u'),
  ('Bangladesh', 'country', 'https://iptv-org.github.io/iptv/countries/bd.m3u'),
  ('Barbados', 'country', 'https://iptv-org.github.io/iptv/countries/bb.m3u'),
  ('Belarus', 'country', 'https://iptv-org.github.io/iptv/countries/by.m3u'),
  ('Belgium', 'country', 'https://iptv-org.github.io/iptv/countries/be.m3u'),
  ('Belize', 'country', 'https://iptv-org.github.io/iptv/countries/bz.m3u'),
  ('Benin', 'country', 'https://iptv-org.github.io/iptv/countries/bj.m3u'),
  ('Bolivia', 'country', 'https://iptv-org.github.io/iptv/countries/bo.m3u'),
  ('Bonaire', 'country', 'https://iptv-org.github.io/iptv/countries/bq.m3u'),
  ('Bosnia and Herzegovina', 'country', 'https://iptv-org.github.io/iptv/countries/ba.m3u'),
  ('Brazil', 'country', 'https://iptv-org.github.io/iptv/countries/br.m3u'),
  ('British Virgin Islands', 'country', 'https://iptv-org.github.io/iptv/countries/vg.m3u'),
  ('Brunei', 'country', 'https://iptv-org.github.io/iptv/countries/bn.m3u'),
  ('Bulgaria', 'country', 'https://iptv-org.github.io/iptv/countries/bg.m3u'),
  ('Burkina Faso', 'country', 'https://iptv-org.github.io/iptv/countries/bf.m3u'),
  ('Cambodia', 'country', 'https://iptv-org.github.io/iptv/countries/kh.m3u'),
  ('Cameroon', 'country', 'https://iptv-org.github.io/iptv/countries/cm.m3u'),
  ('Canada', 'country', 'https://iptv-org.github.io/iptv/countries/ca.m3u'),
  ('Cape Verde', 'country', 'https://iptv-org.github.io/iptv/countries/cv.m3u'),
  ('Chad', 'country', 'https://iptv-org.github.io/iptv/countries/td.m3u'),
  ('Chile', 'country', 'https://iptv-org.github.io/iptv/countries/cl.m3u'),
  ('China', 'country', 'https://iptv-org.github.io/iptv/countries/cn.m3u'),
  ('Colombia', 'country', 'https://iptv-org.github.io/iptv/countries/co.m3u'),
  ('Comoros', 'country', 'https://iptv-org.github.io/iptv/countries/km.m3u'),
  ('Costa Rica', 'country', 'https://iptv-org.github.io/iptv/countries/cr.m3u'),
  ('Croatia', 'country', 'https://iptv-org.github.io/iptv/countries/hr.m3u'),
  ('Cuba', 'country', 'https://iptv-org.github.io/iptv/countries/cu.m3u'),
  ('Curacao', 'country', 'https://iptv-org.github.io/iptv/countries/cw.m3u'),
  ('Cyprus', 'country', 'https://iptv-org.github.io/iptv/countries/cy.m3u'),
  ('Czech Republic', 'country', 'https://iptv-org.github.io/iptv/countries/cz.m3u'),
  ('Democratic Republic of the Congo', 'country', 'https://iptv-org.github.io/iptv/countries/cd.m3u'),
  ('Denmark', 'country', 'https://iptv-org.github.io/iptv/countries/dk.m3u'),
  ('Dominican Republic', 'country', 'https://iptv-org.github.io/iptv/countries/do.m3u'),
  ('Ecuador', 'country', 'https://iptv-org.github.io/iptv/countries/ec.m3u'),
  ('Egypt', 'country', 'https://iptv-org.github.io/iptv/countries/eg.m3u'),
  ('El Salvador', 'country', 'https://iptv-org.github.io/iptv/countries/sv.m3u'),
  ('Equatorial Guinea', 'country', 'https://iptv-org.github.io/iptv/countries/gq.m3u'),
  ('Eritrea', 'country', 'https://iptv-org.github.io/iptv/countries/er.m3u'),
  ('Estonia', 'country', 'https://iptv-org.github.io/iptv/countries/ee.m3u'),
  ('Ethiopia', 'country', 'https://iptv-org.github.io/iptv/countries/et.m3u'),
  ('Faroe Islands', 'country', 'https://iptv-org.github.io/iptv/countries/fo.m3u'),
  ('Finland', 'country', 'https://iptv-org.github.io/iptv/countries/fi.m3u'),
  ('France', 'country', 'https://iptv-org.github.io/iptv/countries/fr.m3u'),
  ('French Guiana', 'country', 'https://iptv-org.github.io/iptv/countries/gf.m3u'),
  ('French Polynesia', 'country', 'https://iptv-org.github.io/iptv/countries/pf.m3u'),
  ('Gambia', 'country', 'https://iptv-org.github.io/iptv/countries/gm.m3u'),
  ('Georgia', 'country', 'https://iptv-org.github.io/iptv/countries/ge.m3u'),
  ('Germany', 'country', 'https://iptv-org.github.io/iptv/countries/de.m3u'),
  ('Ghana', 'country', 'https://iptv-org.github.io/iptv/countries/gh.m3u'),
  ('Greece', 'country', 'https://iptv-org.github.io/iptv/countries/gr.m3u'),
  ('Guadeloupe', 'country', 'https://iptv-org.github.io/iptv/countries/gp.m3u'),
  ('Guam', 'country', 'https://iptv-org.github.io/iptv/countries/gu.m3u'),
  ('Guatemala', 'country', 'https://iptv-org.github.io/iptv/countries/gt.m3u'),
  ('Guernsey', 'country', 'https://iptv-org.github.io/iptv/countries/gg.m3u'),
  ('Guinea', 'country', 'https://iptv-org.github.io/iptv/countries/gn.m3u'),
  ('Guyana', 'country', 'https://iptv-org.github.io/iptv/countries/gy.m3u'),
  ('Haiti', 'country', 'https://iptv-org.github.io/iptv/countries/ht.m3u'),
  ('Honduras', 'country', 'https://iptv-org.github.io/iptv/countries/hn.m3u'),
  ('Hong Kong', 'country', 'https://iptv-org.github.io/iptv/countries/hk.m3u'),
  ('Hungary', 'country', 'https://iptv-org.github.io/iptv/countries/hu.m3u'),
  ('Iceland', 'country', 'https://iptv-org.github.io/iptv/countries/is.m3u'),
  ('India', 'country', 'https://iptv-org.github.io/iptv/countries/in.m3u'),
  ('Indonesia', 'country', 'https://iptv-org.github.io/iptv/countries/id.m3u'),
  ('Iran', 'country', 'https://iptv-org.github.io/iptv/countries/ir.m3u'),
  ('Iraq', 'country', 'https://iptv-org.github.io/iptv/countries/iq.m3u'),
  ('Ireland', 'country', 'https://iptv-org.github.io/iptv/countries/ie.m3u'),
  ('Israel', 'country', 'https://iptv-org.github.io/iptv/countries/il.m3u'),
  ('Italy', 'country', 'https://iptv-org.github.io/iptv/countries/it.m3u'),
  ('Ivory Coast', 'country', 'https://iptv-org.github.io/iptv/countries/ci.m3u'),
  ('Jamaica', 'country', 'https://iptv-org.github.io/iptv/countries/jm.m3u'),
  ('Japan', 'country', 'https://iptv-org.github.io/iptv/countries/jp.m3u'),
  ('Jordan', 'country', 'https://iptv-org.github.io/iptv/countries/jo.m3u'),
  ('Kazakhstan', 'country', 'https://iptv-org.github.io/iptv/countries/kz.m3u'),
  ('Kenya', 'country', 'https://iptv-org.github.io/iptv/countries/ke.m3u'),
  ('Kosovo', 'country', 'https://iptv-org.github.io/iptv/countries/xk.m3u'),
  ('Kuwait', 'country', 'https://iptv-org.github.io/iptv/countries/kw.m3u'),
  ('Kyrgyzstan', 'country', 'https://iptv-org.github.io/iptv/countries/kg.m3u'),
  ('Laos', 'country', 'https://iptv-org.github.io/iptv/countries/la.m3u'),
  ('Latvia', 'country', 'https://iptv-org.github.io/iptv/countries/lv.m3u'),
  ('Lebanon', 'country', 'https://iptv-org.github.io/iptv/countries/lb.m3u'),
  ('Libya', 'country', 'https://iptv-org.github.io/iptv/countries/ly.m3u'),
  ('Liechtenstein', 'country', 'https://iptv-org.github.io/iptv/countries/li.m3u'),
  ('Lithuania', 'country', 'https://iptv-org.github.io/iptv/countries/lit.m3u'),
  ('Luxembourg', 'country', 'https://iptv-org.github.io/iptv/countries/lu.m3u'),
  ('Macao', 'country', 'https://iptv-org.github.io/iptv/countries/mo.m3u'),
  ('Madagascar', 'country', 'https://iptv-org.github.io/iptv/countries/mg.m3u'),
  ('Malaysia', 'country', 'https://iptv-org.github.io/iptv/countries/my.m3u'),
  ('Maldives', 'country', 'https://iptv-org.github.io/iptv/countries/mv.m3u'),
  ('Mali', 'country', 'https://iptv-org.github.io/iptv/countries/ml.m3u'),
  ('Malta', 'country', 'https://iptv-org.github.io/iptv/countries/mt.m3u'),
  ('Martinique', 'country', 'https://iptv-org.github.io/iptv/countries/mq.m3u'),
  ('Mauritania', 'country', 'https://iptv-org.github.io/iptv/countries/mr.m3u'),
  ('Mauritius', 'country', 'https://iptv-org.github.io/iptv/countries/mu.m3u'),
  ('Mexico', 'country', 'https://iptv-org.github.io/iptv/countries/mx.m3u'),
  ('Moldova', 'country', 'https://iptv-org.github.io/iptv/countries/md.m3u'),
  ('Monaco', 'country', 'https://iptv-org.github.io/iptv/countries/mc.m3u'),
  ('Mongolia', 'country', 'https://iptv-org.github.io/iptv/countries/mn.m3u'),
  ('Montenegro', 'country', 'https://iptv-org.github.io/iptv/countries/me.m3u'),
  ('Morocco', 'country', 'https://iptv-org.github.io/iptv/countries/ma.m3u'),
  ('Mozambique', 'country', 'https://iptv-org.github.io/iptv/countries/mz.m3u'),
  ('Myanmar', 'country', 'https://iptv-org.github.io/iptv/countries/mm.m3u'),
  ('Namibia', 'country', 'https://iptv-org.github.io/iptv/countries/na.m3u'),
  ('Nepal', 'country', 'https://iptv-org.github.io/iptv/countries/np.m3u'),
  ('Netherlands', 'country', 'https://iptv-org.github.io/iptv/countries/nl.m3u'),
  ('New Zealand', 'country', 'https://iptv-org.github.io/iptv/countries/nz.m3u'),
  ('Nicaragua', 'country', 'https://iptv-org.github.io/iptv/countries/ni.m3u'),
  ('Niger', 'country', 'https://iptv-org.github.io/iptv/countries/ne.m3u'),
  ('Nigeria', 'country', 'https://iptv-org.github.io/iptv/countries/ng.m3u'),
  ('North Korea', 'country', 'https://iptv-org.github.io/iptv/countries/kp.m3u'),
  ('North Macedonia', 'country', 'https://iptv-org.github.io/iptv/countries/mk.m3u'),
  ('Norway', 'country', 'https://iptv-org.github.io/iptv/countries/no.m3u'),
  ('Oman', 'country', 'https://iptv-org.github.io/iptv/countries/om.m3u'),
  ('Pakistan', 'country', 'https://iptv-org.github.io/iptv/countries/pk.m3u'),
  ('Palestine', 'country', 'https://iptv-org.github.io/iptv/countries/ps.m3u'),
  ('Panama', 'country', 'https://iptv-org.github.io/iptv/countries/pa.m3u'),
  ('Papua New Guinea', 'country', 'https://iptv-org.github.io/iptv/countries/pg.m3u'),
  ('Paraguay', 'country', 'https://iptv-org.github.io/iptv/countries/py.m3u'),
  ('Peru', 'country', 'https://iptv-org.github.io/iptv/countries/pe.m3u'),
  ('Philippines', 'country', 'https://iptv-org.github.io/iptv/countries/ph.m3u'),
  ('Poland', 'country', 'https://iptv-org.github.io/iptv/countries/pl.m3u'),
  ('Portugal', 'country', 'https://iptv-org.github.io/iptv/countries/pt.m3u'),
  ('Puerto Rico', 'country', 'https://iptv-org.github.io/iptv/countries/pr.m3u'),
  ('Qatar', 'country', 'https://iptv-org.github.io/iptv/countries/qa.m3u'),
  ('Republic of the Congo', 'country', 'https://iptv-org.github.io/iptv/countries/cg.m3u'),
  ('Reunion', 'country', 'https://iptv-org.github.io/iptv/countries/re.m3u'),
  ('Romania', 'country', 'https://iptv-org.github.io/iptv/countries/ro.m3u'),
  ('Russia', 'country', 'https://iptv-org.github.io/iptv/countries/ru.m3u'),
  ('Rwanda', 'country', 'https://iptv-org.github.io/iptv/countries/rw.m3u'),
  ('Saint Kitts and Nevis', 'country', 'https://iptv-org.github.io/iptv/countries/kn.m3u'),
  ('Saint Lucia', 'country', 'https://iptv-org.github.io/iptv/countries/lc.m3u'),
  ('Samoa', 'country', 'https://iptv-org.github.io/iptv/countries/ws.m3u'),
  ('San Marino', 'country', 'https://iptv-org.github.io/iptv/countries/sm.m3u'),
  ('Saudi Arabia', 'country', 'https://iptv-org.github.io/iptv/countries/sa.m3u'),
  ('Senegal', 'country', 'https://iptv-org.github.io/iptv/countries/sn.m3u'),
  ('Serbia', 'country', 'https://iptv-org.github.io/iptv/countries/rs.m3u'),
  ('Singapore', 'country', 'https://iptv-org.github.io/iptv/countries/sg.m3u'),
  ('Sint Maarten', 'country', 'https://iptv-org.github.io/iptv/countries/sx.m3u'),
  ('Slovakia', 'country', 'https://iptv-org.github.io/iptv/countries/sk.m3u'),
  ('Slovenia', 'country', 'https://iptv-org.github.io/iptv/countries/si.m3u'),
  ('Somalia', 'country', 'https://iptv-org.github.io/iptv/countries/so.m3u'),
  ('South Africa', 'country', 'https://iptv-org.github.io/iptv/countries/za.m3u'),
  ('South Korea', 'country', 'https://iptv-org.github.io/iptv/countries/kr.m3u'),
  ('Spain', 'country', 'https://iptv-org.github.io/iptv/countries/es.m3u'),
  ('Sri Lanka', 'country', 'https://iptv-org.github.io/iptv/countries/lk.m3u'),
  ('Sudan', 'country', 'https://iptv-org.github.io/iptv/countries/sd.m3u'),
  ('Suriname', 'country', 'https://iptv-org.github.io/iptv/countries/sr.m3u'),
  ('Sweden', 'country', 'https://iptv-org.github.io/iptv/countries/se.m3u'),
  ('Switzerland', 'country', 'https://iptv-org.github.io/iptv/countries/ch.m3u'),
  ('Syria', 'country', 'https://iptv-org.github.io/iptv/countries/sy.m3u'),
  ('Taiwan', 'country', 'https://iptv-org.github.io/iptv/countries/tw.m3u'),
  ('Tajikistan', 'country', 'https://iptv-org.github.io/iptv/countries/tj.m3u'),
  ('Tanzania', 'country', 'https://iptv-org.github.io/iptv/countries/tz.m3u'),
  ('Thailand', 'country', 'https://iptv-org.github.io/iptv/countries/th.m3u'),
  ('Togo', 'country', 'https://iptv-org.github.io/iptv/countries/tg.m3u'),
  ('Trinidad and Tobago', 'country', 'https://iptv-org.github.io/iptv/countries/tt.m3u'),
  ('Tunisia', 'country', 'https://iptv-org.github.io/iptv/countries/tn.m3u'),
  ('Turkiye', 'country', 'https://iptv-org.github.io/iptv/countries/tr.m3u'),
  ('Turkmenistan', 'country', 'https://iptv-org.github.io/iptv/countries/tm.m3u'),
  ('Uganda', 'country', 'https://iptv-org.github.io/iptv/countries/ug.m3u'),
  ('Ukraine', 'country', 'https://iptv-org.github.io/iptv/countries/ua.m3u'),
  ('United Arab Emirates', 'country', 'https://iptv-org.github.io/iptv/countries/ae.m3u'),
  ('United Kingdom', 'country', 'https://iptv-org.github.io/iptv/countries/uk.m3u'),
  ('United States', 'country', 'https://iptv-org.github.io/iptv/countries/us.m3u'),
  ('Uruguay', 'country', 'https://iptv-org.github.io/iptv/countries/uy.m3u'),
  ('Uzbekistan', 'country', 'https://iptv-org.github.io/iptv/countries/uz.m3u'),
  ('Vatican City', 'country', 'https://iptv-org.github.io/iptv/countries/va.m3u'),
  ('Venezuela', 'country', 'https://iptv-org.github.io/iptv/countries/ve.m3u'),
  ('Vietnam', 'country', 'https://iptv-org.github.io/iptv/countries/vn.m3u'),
  ('Western Sahara', 'country', 'https://iptv-org.github.io/iptv/countries/eh.m3u'),
  ('Yemen', 'country', 'https://iptv-org.github.io/iptv/countries/ye.m3u'),
  ('Zimbabwe', 'country', 'https://iptv-org.github.io/iptv/countries/zw.m3u')
on conflict (url) do nothing;
